
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/context/theme";
import AuthProvider from "@/components/AuthProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <ThemeProvider>
      <html lang="en">
        <body className={inter.className}>
          <AuthProvider>
          <Navbar />
          {children}
          </AuthProvider>
        </body>
      </html>
    </ThemeProvider>
  );
}
